### ISSUE TITLE
brew cask doesn't work :(

### ISSUE THREAD

**Issue by ha404** [dteoh/SlowQuitApps#10]
I think it just needs to be linked up again:
`brew cask install slowquitapps` fails

**Comment by dteoh** [comment]
Yeah, I found that on first install, you have to run that command twice. Don't know why.

**Comment by ha404** [comment]
![screen shot 2017-02-21 at 4 12 14 pm](https://cloud.githubusercontent.com/assets/567126/23191095/a04ef79c-f850-11e6-9c38-a32623c3aea5.png)
No bueno still :(

**Comment by dteoh** [comment]
You did run the tap command first, right?

**Comment by ha404** [comment]
You, sir, are a genius! 👍 

Do you happen to know why I need to tap it first? I've never had to do that to my apps until now.

**Comment by dteoh** [comment]
Great 👍 

Some apps have their cask formulas in the default repository, so you don't need to tap anything. I didn't submit SQA to the defaults because it is for "stable" apps, and also I didn't really want releases to be delayed by a third-party.
