### ISSUE TITLE
Doesn't work on window switcher?

### ISSUE THREAD

**Issue by koro-xx** [dteoh/SlowQuitApps#13]
I found myself accidentally closing apps while using the window switcher (command+tab). That's especially bad because due to SlowQuitApp I am being a little less careful about cmd+q, so this tends to happen more often than before.

If it wasn't clear: hitting cmd+tab, then releasing tab without letting cmd go, then hitting q will immediately close the selected app...

I don't think this is intended behavior, or is it?

**Comment by dteoh** [comment]
I didn't know that method of closing apps was possible. I will have to investigate which app is handling the keystrokes in this scenario.

**Comment by dteoh** [comment]
It doesn't look like I can intercept key presses while the window switcher is active.
