### ISSUE TITLE
App not working.

### ISSUE THREAD

**Issue by LukeJansen** [dteoh/SlowQuitApps#18]
When i hold CMD+Q, the animation pops up for a single frame and then disappears, have tried closing and reopening. Have the latest version of SQA. Even when holding CMD+Q for a while the app doesnt quit

**Comment by dteoh** [comment]
Well that's not right.

* what version of OSX are you using?
* what app are you trying to quit?
* are you using other global shortcut apps?

Thanks.

**Comment by LukeJansen** [comment]
Version: 10.13.2
App: All apps
No other global apps

**Comment by wizonesolutions** [comment]
I was experiencing this and went up to 0.3.0...but still the same behavior (at first, it just didn't work, but `killall SlowQuitApps` and starting it up again got me past that.

**Comment by dteoh** [comment]
Version 0.3.1 is now available, please give this one a go. Thanks!
