### ISSUE TITLE
Does not work when caps lock is on

### ISSUE THREAD

**Issue by bcooney** [dteoh/SlowQuitApps#2]
In fact, this doesn't work if caps lock is on. When caps lock is on ("Q"), the on-screen circle flashes quickly but does not begin. Only when caps lock is off ("q") does the on-screen circle engage and begin to count down. 

In reality, it's Command+q, not Command+Q. Pedantic, I know :)

**Comment by dteoh** [comment]
Interesting! I wasn't aware that the hotkey API was case-sensitive, will have to look into this.

**Comment by dteoh** [comment]
Fixed!

New binary published on releases page.

**Comment by bcooney** [comment]
Nice one! Thanks
