### ISSUE TITLE
Changing delay doesn't work

### ISSUE THREAD

**Issue by f0rtis** [dteoh/SlowQuitApps#20]
I tried to change delay time using command from readme using
`defaults write com.dteoh.SlowQuitApps delay -int 7000`

Now `defaults read com.dteoh.SlowQuitApps`
shows
````
{
    delay = 7000;
}
````

But delay still is 2sec. I tried re-launching the app, but it didn't help.
I'm using Mac OS 10.13.2

**Comment by dteoh** [comment]
Seems like there is a problem with the automatic killing of other app instances.

Please try doing a force quit of the app through Activity Monitor.

**Comment by f0rtis** [comment]
I tried force quit a few times, but it also didn't help. However after restarting a laptop, delay changed to set value. And then I tried to change delay again and it worked after force quit.
So, if you changed delay and it doesn't work - you need:
1) Force quit the app;
2) If 1 option doesn't work, then restart the system.

It looks like a good idea to add this information to the readme file.

**Comment by dteoh** [comment]
A force quit and reboot is definitely not something that I want to promote as being normal. Having to reboot doesn't seem right to me, but I don't confess to understanding the internals of NSDefaults well enough to rule it out.

The good thing after debugging this issue, is that I have a better understanding of why the app just won't work for some people now, and will definitely make it more robust.

**Comment by dteoh** [comment]
Updated README to include instructions about killing SQA.

Automatic app termination only worked in my dev environment.
