### ISSUE TITLE
Delay does not change after executing command

### ISSUE THREAD

**Issue by Scosh** [dteoh/SlowQuitApps#21]
Hi.

I've been using the app for a couple of days now and really like it. 👌🙃

I'd like to change a single thing, however, and that would be the **delay timer.**

On my system it seems to currently sit at **3 seconds.**

So I *have* successfully changed it from the 1 second default at some point in the past. But for whatever reason, SlowQuitApps doesn't seem to acknowledge any new delays I try to specify.

I'm actually trying to get it to be **a bit shorter than 3 seconds** at the moment.

But even trying to specify much more extreme defaults like 500 milliseconds …

```
$ defaults write com.dteoh.SlowQuitApps delay -int 500
```

… which should, of course, be a noticeable difference vs. 3000 milliseconds …

doesn't change anything about the 3 second delay. Even after restarts of macOS, the delay still stays at 3 seconds.

---

Am I doing something wrong? Is there a way to restart SlowQuitApps or send an update about the new delay to it that I've missed in the README?

I installed the app using **homebrew** (brew cask), and a `$ brew cask info slowquitapps` reveals I appear to have the latest version.

```
slowquitapps: 0.3.0
https://github.com/dteoh/SlowQuitApps
/usr/local/Caskroom/slowquitapps/0.3.0 (64B)
From: https://github.com/dteoh/homebrew-sqa/blob/master/Casks/slowquitapps.rb
==> Name
SlowQuitApps
==> Artifacts
SlowQuitApps.app (App)
```
My macOS version is **High Sierra.** (10.13.2)  
My hardware is the **2015 MacBook Pro.**

**Comment by dteoh** [comment]
There are a few issues I need to rework surrounding the auto-kill and the hotkey registration.

I haven't upgraded to High Sierra, so I'm also speculating that there might have been a change in the way the preferences system works when an app is reading from it and is still alive, but I need to fix the other issues first to try to rule this out.

In the mean time, can you try:

1. `$ killall SlowQuitApps`
2. `$ defaults read com.dteoh.SlowQuitApps` to check the current preferences
3. Change the delay
4. `$ defaults read com.dteoh.SlowQuitApps` to confirm the new preferences are in place
5. Start the app again.

If after step 5 it still doesn't work, try again from step 1 but reboot at step 5.

Thank you.

**Comment by dteoh** [comment]
Version 0.3.1 has been release, please try this version before running the above steps. Thanks!

**Comment by dteoh** [comment]
Version 0.3.2 has been released.

`killall SlowQuitApps` is now a required part of the upgrade and customization process. The autokill never worked because macOS will prevent apps from launching multiple times.

**Comment by Scosh** [comment]
Excellent. It works perfectly now after updating to 0.3.2 and using the described methods from the README. 👏

I believe this issue may now be closed.

**Comment by dteoh** [comment]
Great, thanks!
