### ISSUE TITLE
Feature Proposal: Add option to enable SlowQuit for just the apps listed.

### ISSUE THREAD

**Issue by mohakshah** [dteoh/SlowQuitApps#27]
The app currently operates in the following manner:
- Enable the slow quit functionality globally, except for the apps listed in whitelist.

I would like to propose an option which allows the opposite operation mode, i.e.
- _Disable_ the slow quit functionality globally and enable it just for the apps listed in the whitelist.

The feature could be offered by simply adding a boolean switch such as `invertList`. This switch, which defaults to false (i.e. the current operation mode), when set to true, would only activate slow quit on the apps listed in the whitelist.

I already have an implementation of this feature in a local branch. If you are interested in adding this feature, please let me know, and I'll create a PR.

**Comment by dteoh** [comment]
Sounds good, please send a PR 👍

**Comment by dteoh** [comment]
Thank you for contributing, feature merged and released to v0.4.0.
