### ISSUE TITLE
Command + Tab Quitting overrides SlowQuit

### ISSUE THREAD

**Issue by cpeak** [dteoh/SlowQuitApps#30]
When Command Tabbing through applications and I press Command + Q applications quit instantly, ignoring the SlowQuitApps functionality.

Example GIF: Open Preview and quit normally. Command + Tab over to System Preferences and release the Command + Tab action. Quit normally. Command + Tab over to Firefox and WITHOUT releasing Command I press the Q to instantly quit, then tab over to TextWrangler and do the same.

![ezgif-5-d293482812](https://user-images.githubusercontent.com/1455031/40436124-e84399fc-5e77-11e8-9943-d35dfd88984b.gif)

It seems the system is ignoring the SlowQuitApps functionality when in the Command + Tab action.

Thanks for the app, I love it!

**Comment by dteoh** [comment]
Related to #13 

Doing this probably requires some dark magic to override the window switcher app: https://raamdev.com/2007/replace-os-x-commandtab-with-witch/

**Comment by ravicious** [comment]
I have to say that I considered such behavior to be a feature. 😶 If I want to quickly close a couple of apps, I always have the option to use cmd + tab quitting.

Unfortunately, after the update to Mojave, pressing Q while the App Switcher is present closes the switcher along with the selected app and I have to press cmd + tab to bring it up again.

![slowquitapps_on_mojave](https://user-images.githubusercontent.com/27113/48668774-28abc400-eaf6-11e8-9cf5-34c138964e1c.gif)

**Comment by dteoh** [comment]
At this stage, SQA will not override App Switcher behavior. Making sure that SQA will not interfere with the App Switcher will be handled in #55.
