### ISSUE TITLE
Doesn't work with dvorak keyboards

### ISSUE THREAD

**Issue by rudedogdhc** [dteoh/SlowQuitApps#31]
In a Dvorak keyboard, the ⌘Q keystroke actually maps to ⌘X. So the app doesn't correctly intercept the correct keystroke.

**Comment by dteoh** [comment]
I don't use Dvorak so I need some guidance.

Is this an external keyboard? A software emulation of the Dvorak layout on a Qwerty keyboard?

**Comment by rudedogdhc** [comment]
It's just a keyboard mapping: System Preferences -> Language & Region -> Keyboard Preferences, hit the + button to add a new keyboard mapping. 

I know that there are other apps around that intercept keystrokes and are able to handle different keyboard mappings, so it's definitely possible. I have no idea how it's done, though.

**Comment by dteoh** [comment]
Dvorak (and other keyboard layouts) should now be supported in Version 0.5.0.
