### ISSUE TITLE
Does not work on macOS Mojave

### ISSUE THREAD

**Issue by stefandesu** [dteoh/SlowQuitApps#32]
After installing macOS Mojave on my second machine, I noticed that SlowQuitApps stopped working. The overlay would show up shortly but then immediately stop. I had this happen on High Sierra occasionally as well, but restarting SlowQuitApps usually fixed it. On Mojave, the error occurs every time.

I checked out the repository and tried running it locally, and with a few NSLog statements I figured it where it fails. In `SQACmdQStream.m` on line 54, `CGEventSourceKeyState(kCGEventSourceStateHIDSystemState, kVK_ANSI_Q);` returns False even though the Q key is pressed. Apparently, it still recognized the first keypress of CMD + Q, but just not that the Q key is still pressed. If I change line 43 in the same file to `const BOOL pressed = cmdPressed;`, the app works again (but just doesn't recognize if you stop holding Q which is annoying). 

Any ideas on how to fix this?

**Comment by dteoh** [comment]
I don't have Mojave yet.

You can try:

* changing from `kCGEventSourceStateHIDSystemState` to `kCGEventSourceStateCombinedSessionState` ([docs][1])
* recompiling the app using the Mojave SDK

[1]: https://developer.apple.com/documentation/coregraphics/cgeventsourcestateid

**Comment by StefanDesu** [comment]
I think I did try the first one, but not the second one yet. Will try it later and report back!

**Comment by stefandesu** [comment]
Same issue when compiled with Xcode 10 beta. Also tried `kCGEventSourceStateCombinedSessionState`. Both `CGEventSourceKeyState(kCGEventSourceStateHIDSystemState, kVK_ANSI_Q);` and `CGEventSourceKeyState(kCGEventSourceStateCombinedSessionState, kVK_ANSI_Q);` return False. I also iterated through all key codes and only 55 (kVK_Command) returns True. Could this be a bug in Mojave?

**Comment by dteoh** [comment]
Thank you for investigating!

For now, it looks like a bug in Mojave.

**Comment by kikandychan** [comment]
solved
open MacOS **system preference** 
then go to **security/privacy**
then click on **privacy**
scroll down to **accessibility** 
then **unlock** 
then **add slowquitapps.app to the list** 
again, add the app to application data to allow this app access to application data

**Comment by stefandesu** [comment]
Awesome, that worked! And there's enough time to put that information into the app as a popup or something.

**Comment by dteoh** [comment]
Great! I will look into adding this information in an alert popup.

**Comment by dteoh** [comment]
Thank you both for investigating!

Version 0.4.1 asks for Accessibility permissions on launch.
