### ISSUE TITLE
Adding a icon or logo

### ISSUE THREAD

**Issue by leomikezee** [dteoh/SlowQuitApps#35]
Can claim a icon or logo [here](https://github.com/arasatasaygin/openlogos). Personally recommend [this one](https://camo.githubusercontent.com/ed4d7fbb14ee844abed760c77e55c4dbf3153309/68747470733a2f2f6172617361746173617967696e2e6769746875622e696f2f6f70656e6c6f676f732f6c6f676f732f696e73706563746f722e6a7067).

**Comment by dteoh** [comment]
Standalone, I think those logos look great, but I'm not feeling it in terms of what this app does + how it would feel with macOS (they look very Web 2.0/Bootstrap/Flat design-ish).

So for now I suppose I will let this ticket be an open call/request for an icon contribution 🙏

I apologize in advance if I end up not liking the submissions 🙇

**Comment by yokhoe** [comment]
@JayBrown Can you PNG/ICO this? I'd like to custom set it for my own :)

**Comment by fancyme** [comment]
My version

![SlowQuitApps](https://user-images.githubusercontent.com/1077730/60185660-96596480-982a-11e9-9141-55d1cb1cf585.png)

![11](https://user-images.githubusercontent.com/1077730/60185513-5abe9a80-982a-11e9-8d9a-f7e2774903b7.png)

**Comment by dteoh** [comment]
@fancyme Your icon looks great, it feels very at home on your dashboard :)

Would you be willing to contribute this and prepare the various icon sizes listed in [Apple's guidelines][1]?

[1]: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by fancyme** [comment]
@dteoh With pleasure. I hope that I did everything right ☺️

[SlowQuitApps icons.zip](https://github.com/dteoh/SlowQuitApps/files/3336449/SlowQuitApps.icons.zip)

**Comment by dteoh** [comment]
@fancyme Thanks! Released in version 0.7.3, and added credits in the readme file.
