### ISSUE TITLE
Does not work anymore with Mac OS Mojave

### ISSUE THREAD

**Issue by kantlove** [dteoh/SlowQuitApps#37]
Hi, I'm using Macbook Pro 2017 and Mac OS Mojave Beta 2. The app does not work anymore.

When I hold Cmd+Q, the animation appears briefly (~0.5s) and disappears. The current app does not quit.

**Comment by dteoh** [comment]
Try updating the app to the latest version.

(reported in #32)

**Comment by kantlove** [comment]
Updating the app as mentioned in #32 solves the problem. Thanks a lot 👍
