### ISSUE TITLE
Broken in macOS Mojave.

### ISSUE THREAD

**Issue by sunaiwen** [dteoh/SlowQuitApps#39]
The quitting animation is blinking when holding `cmd + q`, and could not quit the app.

**Comment by dteoh** [comment]
Is this with the latest version of the app?

**Comment by sunaiwen** [comment]
Yes, I tried with the latest v0.5.0.

**Comment by Shagon94** [comment]
can confirm, it doesn't work anymore

**Comment by glimpsed** [comment]
Had the same problem, reinstalled the app, gave it permission to control the computer via Security & Privacy > Privacy > Accessibility, and now it works 👍 @sunaiwen @dteoh @Shagon94

**Comment by dteoh** [comment]
@glimpsed Great, thanks!

**Comment by sunaiwen** [comment]
@glimpsed Good Job! BTW, you could just restart it.
