### ISSUE TITLE
[BUG] Constant alert sounds in most apps when quitting them with v0.6.0

### ISSUE THREAD

**Issue by JayBrown** [dteoh/SlowQuitApps#42]
I'm getting constant alert sounds, when quitting applications with version 0.6.0. Doesn't happen in every application, e.g. Firefox and GitHub Desktop seem to be fine, but with the majority, e.g. iTerm, BBEdit, Apple Mail, Twitteriffic and many others, there are constant alert sounds. Tried quitting and re-opening the affected apps, but the bug prevails.

macOS 10.13.6
SlowQuitApps is in the Accessibility list and ticked

**Comment by JayBrown** [comment]
Nope, Firefox has the problem too. If a window is open, there are no alert sounds, only one alert sound when Firefox has finally quit. When no window is open, then there are alert sounds immediately.

(GitHub Desktop is fine, though.)

**Comment by dteoh** [comment]
Please downgrade to 0.5.0. I will be dropping support for versions of macOS older than Mojave.

I don't have the time to debug these low level APIs on every OS and the changing undocumented behaviour present in these APIs.

**Comment by JayBrown** [comment]
OK, have already downgraded. Thank you for the info.
