### ISSUE TITLE
How to avoid typing "qqq" to the next app?

### ISSUE THREAD

**Issue by borekb** [dteoh/SlowQuitApps#43]
Thanks for this awesome utility! What I struggle with a bit is:

- I press and hold Cmd+Q to quite the current app.
- After one second, it quits
- ... but some next app gains focus and "qqqq" is typed there.

So in practice, it's like playing a game to release the keys at _exactly_ one second, otherwise it has this sideeffect.

No ideas what to do about it but I thought it's worth opening an issue for it.

**Comment by dteoh** [comment]
I am not experiencing this behaviour.

I opened up Stickies and Notes. I held down both keys, let SQA quit Notes for me, and continued holding down both keys after Stickies has gained focus. No repeated q's were inserted into the document. If I release the command key first, I get a single "q" inserted. If I release q first, nothing out of the ordinary happens.

**Comment by borekb** [comment]
You're right, I was releasing the keys in the wrong order. Will be more careful next time :)
