### ISSUE TITLE
Mojave 10.14.1: noticed SQA v0.5.0 problems with Firefox 63.0.3 and old phpBB

### ISSUE THREAD

**Issue by JayBrown** [dteoh/SlowQuitApps#47]
This is probably related to the alert sound beeping when using v0.6.0 etc., deprecated APIs etc., but I have just noticed that version 0.5.0 of SQA on Mojave 10.14.1 messed up the tags (bold, italics etc.), emoticons, and color pickers on a forum using older phpBB, when loaded in the new Firefox 63.0.3, meaning that nothing happened, when you clicked on them.

After quitting and relaunching SlowQuitApps, everything was back to normal again. Will have to see if this happens again. (Note: I can't update to v0.6.0 because of the constant alert sound when quitting some applications.)

**Comment by dteoh** [comment]
Honestly, this sounds pretty outlandish. I get that SQA is not working 100% but this sounds like a coincidence with some other problem. I also cannot take any action with a bug report that is vague about the details.
