### ISSUE TITLE
Doesn't require Q to be held

### ISSUE THREAD

**Issue by 00dani** [dteoh/SlowQuitApps#5]
If you only tap ⌘Q but keep holding ⌘, which is I think a common way to type shortcuts, SlowQuitApps still counts down and quits your app. By contrast, Chrome's Warn Before Quitting feature requires both keys to be held.

**Comment by dteoh** [comment]
Yeah, I had problems with requiring both keys to be held when I programmed this. Will have to research how to do this properly.

**Comment by 00dani** [comment]
Ah, fair enough. I've only done the tiniest bit of macOS GUI code and and I can appreciate that it's kind of a nightmare. 😊  Definitely something to look into!

**Comment by dteoh** [comment]
Fixed!

New binary published on the releases page.
