### ISSUE TITLE
SQA requests autostart on login after every login

### ISSUE THREAD

**Issue by Scosh** [dteoh/SlowQuitApps#51]
So, I don't know if this is perhaps related to #44 because of the "problems after restarting" similarities. In my case things definitely aren't so dire: SQA is still generally working well for me after the Mojave update.

The only peculiarity is a minor annoyance. The app keeps asking me to register it as a login item every time I log back into my system after a shut down / restart.

![screenshot 2018-12-03 at 11 25 43](https://user-images.githubusercontent.com/5603235/49369250-46ca1480-f6f1-11e8-8140-7adb9cd03778.png)

And it will also only work for that following session if I hit `Yes` on that dialogue.

SQA is in my login items. But as far as I can remember, it has been anyway even before the dialogue kept popping up.

![screenshot 2018-12-03 at 11 39 26](https://user-images.githubusercontent.com/5603235/49369316-6f520e80-f6f1-11e8-9a0e-079f42774fa3.png)

This is for sure something I can live with if it's currently not fixable with the new Mojave API / whatever Apple decided to change to make developers' lives harder this time around. Or maybe I'm just being an idiot and missing something I can do myself to fix this. Either way, I wanted to point it out, and would still appreciate help if anyone here can give it.

**Comment by dteoh** [comment]
The latest major release of the app uses non-deprecated APIs to achieve this. Can you confirm the following:

* the application version is 0.7.x
* the process list in Activity Monitor includes "SlowQuitAppsLauncher"

I don't think that "SlowQuitApps" should be in the Login Items anymore, but the bundled launcher application.

**Comment by Scosh** [comment]
Yes, my version is `0.7.1`, from the homebrew cask.

```
$ brew cask info slowquitapps
slowquitapps: 0.7.1
https://github.com/dteoh/SlowQuitApps
/usr/local/Caskroom/slowquitapps/0.7.1 (64B)
From: https://github.com/dteoh/homebrew-sqa/blob/master/Casks/slowquitapps.rb
==> Name
SlowQuitApps
==> Artifacts
SlowQuitApps.app (App)
```

The Activity Monitor shows a `SlowQuitApps` as well as a `SlowQuitAppsLauncher` process:

![screenshot 2018-12-05 at 22 25 25](https://user-images.githubusercontent.com/5603235/49545186-31194280-f8dd-11e8-900f-140cecf17d97.png)

**Comment by dteoh** [comment]
Your process list looks right. The correct event sequence is:

* launcher app starts
* launcher app launches the main app
* main app starts
* main app checks for presence of launcher app in workspace to determine if auto start is enabled

It seems that in your case, the main app is starting before the launcher app. This is probably because of the "Login Items" entry. I think that if you delete that entry, and restart, you _shouldn't_ encounter this issue. At least on my machine, I don't have that entry but auto launch still works.

I don't think I can automatically clean up that "Login Item" entry because the APIs for that is pretty much gone when compiling with the latest SDK.

**Comment by 7Ds7** [comment]
I was about to write about the same issue, i upgraded to v0.7.1 some time ago and this has been happening to me since. 
After going back to [karabiner](https://github.com/tekezo/Karabiner-Elements) and back (because i really just want the cmd + q functionality, i did

```
killall SlowQuitApps
``

(installed and uninstalled karabiner but i guess that is not the point)

```
killall SlowQuitAppsLauncher
```

And after rebooted and there was no more "automatically launch question" at login

**Comment by Scosh** [comment]
> I think that if you delete that entry, and restart, you *shouldn't* encounter this issue.

Okay, I tried this just now and it appears to have worked! There is no more dialogue box on start-up but SQA still launches and is running. Thanks!

> I don't think I can automatically clean up that "Login Item" entry because the APIs for that is pretty much gone when compiling with the latest SDK.

Okay, if it can't be fixed with code, do you think a mention of this issue and its hotfix in the README could help others and would be appropriate? Or don't you think it will affect enough people to be worth it. I mean, it did @7Ds7 also, but they at least came up with their own solution, so I dunno.

I could draft an explanation of this problem and the fix for the README once I find a bit more time soon.

**Comment by dteoh** [comment]
I amended the release notes for v0.7.x to include the instructions and a link to this issue.

**Comment by Scosh** [comment]
> I amended the release notes for v0.7.x to include the instructions and a link to this issue.

Okay, great!

**Comment by borekb** [comment]
For anyone googling this as I was, the trick is to remove SlowQuitApps from the **Login Items** list as mentioned here: https://github.com/dteoh/SlowQuitApps/issues/51#issuecomment-444692512. (It's a bit buried there but thanks for the hint @dteoh!)

**Comment by pronouncedJerry** [comment]
it's creeped up again

**Comment by fancyme** [comment]
Thanks!
