### ISSUE TITLE
CMD + TAB and then CMD + Q using SQA only allows one app to be quit

### ISSUE THREAD

**Issue by mstnorris** [dteoh/SlowQuitApps#55]
If I bring up the app switcher using CMD + TAB and then quit an app using CMD + Q it will only allow me to quit that one app and then it gets stuck. I have to invoke the app switcher again to be able to quit another app.

As a side note just as an observation; in Mojave this doesn't respect SQA and quits the app instantly but I won't comment either way as to whether it should or shouldn't as I don't have an opinion on that.

**Comment by peteygao** [comment]
>in Mojave this doesn't respect SQA and quits the app instantly but I won't comment either way as to whether it should or shouldn't as I don't have an opinion on that.

As a user, my two cents is that it should respect SQA--especially since the SQA spinner overlay still _appears_ when using the App Switcher + `CMD + Q`.

Alternatively, make it consistent if it shouldn't respect SQA by not displaying the overlay when the App Switcher is visible.

**Comment by jeffhuys** [comment]
I remember this working in an older version of SQA. I'm going to try to downgrade to that version as I use this a lot (after a long week of working I don't want to be reminded of everything in the weekend).

As for my two cents about the discussion whether it should be on a timer as well, using the app switcher: I think this would be better as an option. I would use it as the "original" app switcher: immediate quitting of apps.

**Comment by dteoh** [comment]
The app was never aware of the switcher, the old behaviour was just a happy accident.

Detecting if the switcher is open, now that's the first problem to solve...

**Comment by dteoh** [comment]
Fixed in v0.8.0. SQA will not attempt to override the App Switcher's native behaviour.
