### ISSUE TITLE
After a restart, I keep getting asked if SQA should start at login

### ISSUE THREAD

**Issue by pronouncedJerry** [dteoh/SlowQuitApps#56]
MacBook Pro 2018, macOS 10.14.3

**Comment by Saratxe** [comment]
Same here. I didn't have SQA in my Login Items! After every restart I get asked. Mojave 10.14.3 iMac 2017

**Comment by inovek** [comment]
Updated yesterday with the hope to get rid of this issue. (seeing this message already for months, maybe a half year)

But still existing. (current Mojave on a iMac18,3)

**Comment by dteoh** [comment]
Please see #51.

If you still see this issue, please exit SlowQuitApps. Then find every instance of SlowQuitApps on your hard drive, and delete it, restart, and re-install.

**Comment by pronouncedJerry** [comment]
dupe of #51
