### ISSUE TITLE
An option to show the App Name that is being terminated in the graphic

### ISSUE THREAD

**Issue by matthewshannon** [dteoh/SlowQuitApps#60]
As per subject, any chance you could add the ability to render the name of the app being terminated.

Having switched to a mac just recently, I've lost work a few times in Safari by accidentally triggering the command-q - having intended to only close the window instead (command-w).

Combine this with the system setting I'm leveraging that hides the menu bar, it is sometimes hard to know which application is actually active as well, particularly when many apps are rendered on screen.

**Comment by dteoh** [comment]
Added in v0.8.0.

**Comment by matthewshannon** [comment]
Thanks!  Works great.
