### ISSUE TITLE
Can not register ⌘Q

### ISSUE THREAD

**Issue by dErangaPrasad** [dteoh/SlowQuitApps#61]
When app launching alert popup saying can not register ⌘Q. and app terminates immediately  
<img width="420" alt="Screen Shot 2019-09-30 at 11 58 22 AM" src="https://user-images.githubusercontent.com/3157239/65854321-f7d52600-e379-11e9-9765-6973a7874a86.png">

**Comment by dteoh** [comment]
It is as the alert message says. There is another app currently running that is already handling ⌘Q, so SQA cannot be used. You will have to quit the other app.

**Comment by dErangaPrasad** [comment]
@dteoh Thanks for the reply. I tried that. But didn't help. Resolved by adding app to accessibility in Privacy settings.
