### ISSUE TITLE
Feature Proposal: Enable only if more than one window is open

### ISSUE THREAD

**Issue by r3a1d3a1** [dteoh/SlowQuitApps#62]
My main problem with Cmd+Q is when more than one window of an app like XCode is open and I inadvertently try to close one window, having forgotten about the others, especially if they are on other desktops.
It would be great to have the delay functionality kick in only when multiple windows of an app are detected. Or maybe just a simple warning to remind me susceptibility of other windows to the imminent closure.

**Comment by dteoh** [comment]
I can only say that in macOS "closing a window" is not the same as "quitting an app".

**Comment by r3a1d3a1** [comment]
Captain Obvious

**Comment by dteoh** [comment]
No need for insults.

Gentle reminder that open source devs have zero obligation to implement every feature request.
