### ISSUE TITLE
SlowQuitApps cannot register ⌘Q

### ISSUE THREAD

**Issue by raadopt** [dteoh/SlowQuitApps#63]
Updated the app and can't start it now:

SlowQuitApps cannot register ⌘Q
Another application has exclusive control of ⌘Q, SlowQuitApps cannot continue. SlowQuitApps will exit.

<img width="420" alt="Screenshot 2019-10-27 at 7 34 13 PM" src="https://user-images.githubusercontent.com/56934567/67638751-e9364c00-f8f0-11e9-8bc3-4c6cbfb3a37d.png">

Previous version was working without any issues. 
How to determine which app has exclusive control of ⌘Q?

**Comment by dteoh** [comment]
I don't know what version you upgraded from, so can you try running the following steps to hopefully get a clean environment:

1. In terminal, `killall SlowQuitApps`
2. Open up "System Preferences". Go to "Security & Privacy" -> "Privacy". Remove "SlowQuitApps" from the list.
3. Follow the instructions for removing SQA from the login items list: https://github.com/dteoh/SlowQuitApps/releases/tag/v0.7.0
4. Reboot
5. Start SQA

If it still doesn't work, you might be running another kind of key binding software that has also hooked in the Cmd-Q.

**Comment by raadopt** [comment]
Thanks a lot, that helped!
