### ISSUE TITLE
Broken on macOS Catalina after unexpected shutdown

### ISSUE THREAD

**Issue by isgilman** [dteoh/SlowQuitApps#70]
I have been using SQA since macOS Mojave and it had continued to work on Catalina 10.15.2 until my machine restarted because of an unexpected error. When it rebooted SQA was not functioning, although it shows up in Activity Monitor normally. I have encountered this problem before and resolved it by completely uninstalling and reinstalling with `brew cask` etc, followed by removing and re-adding SQA access in System Preferences > Accessibility. I haven't received any error messages, the app appears to launch fine, and processes are associated with it (SlowQuitApps and SlowQuitAppsLauncher) but all apps close immediately with cmd+Q.

- macOS Catalina 10.15.2
- Homebrew 2.2.5
- slowquitapps: 0.8.0

**Comment by dteoh** [comment]
🤷‍♂ Works for me on 10.15.3.

Unexpected shutdown isn't something I can replicate to see what's wrong. My only suggestion is to remove the accessibility settings, completely uninstall the app (as you have done), reboot, check the process list to make sure it isn't there, then re-install (and go through the whole "right click open and allow dangerous app" process).

**Comment by AlexYang-yz** [comment]
i had the same problem, but it seems to not caused by machine restart, it just cant work a few time suddenly, and it show up when i used ps -ef in the terminal. it can work when I killed the process and restart it. So do you know what's the problem is ?  And how to solve it ? 

macOS Catalina 10.15.2
slowquitapps: 0.8.0

**Comment by matthewshannon** [comment]
I've had similar issues after updating the app itself.

Check /var/log/system.log to see if it mentions a trust quarantine issue ...

SlowQuitApps

/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump | grep SlowQuit

/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill

tail -f /var/log/system.log



Jan 14 12:42:21 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1226]): Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.dteoh.SlowQuitAppsLauncher
Jan 14 12:42:21 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1226]): Service exited with abnormal code: 78
Jan 14 12:42:21 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 12:42:31 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1227]): Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.dteoh.SlowQuitAppsLauncher
Jan 14 12:42:31 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1227]): Service exited with abnormal code: 78
Jan 14 12:42:31 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 12:42:41 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1231]): Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.dteoh.SlowQuitAppsLauncher
Jan 14 12:42:41 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1231]): Service exited with abnormal code: 78
Jan 14 12:42:41 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 12:42:51 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1236]): Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.dteoh.SlowQuitAppsLauncher
Jan 14 12:42:51 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1236]): Service exited with abnormal code: 78
Jan 14 12:42:51 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 12:43:01 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1237]): Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.dteoh.SlowQuitAppsLauncher
Jan 14 12:43:01 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher[1237]): Service exited with abnormal code: 78
Jan 14 12:43:01 mshannon-mac com.apple.xpc.launchd[1] (com.dteoh.SlowQuitAppsLauncher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.


sudo xattr -d -r -s com.apple.quarantine /Applications/SlowQuitApps.app

**Comment by isgilman** [comment]
This morning I tried again after the above comments but it still isn't working. Specifically I 

1. Checked the `system.log` for any quarantine notes, but found none
2. Used `killall SlowQuitApps` and `kill` to terminate all of the processes associated with SQA
3. Removed SlowQuitApps from System Preferences > Accessibility
4. Uninstalled SQA with `brew cask uninstall slowquitapps`
5. Updated to macOS 10.15.3
6. Reinstalled SQA, gave Accessibility permissions, and then opened with right-click

**Comment by dteoh** [comment]
Hey, can you all try following the steps posted by @isgilman with a change to step 6:

Right after the install:

* Open terminal, cd into the directory containing SlowQuitApps.app
* Run `xattr -r -s -d com.apple.quarantine SlowQuitApps.app` - This will delete the quarantine flags on both SQA and the launcher app
* Run `spctl --add --label 'Approved' SlowQuitApps.app` 
* Run `spctl --add --label 'Approved' SlowQuitApps.app/Contents/Library/LoginItems/SlowQuitAppsLauncher.app`
* Open SQA, grant accessibility permissions. Exit SQA after grant. Re-open.

FWIW, I'm still not experiencing any issues, but it could just be that I haven't tripped the new security system in some special way...

**Comment by isgilman** [comment]
Just tried these steps but it's still not behaving. Are there any log files that would be helpful?

**Comment by isgilman** [comment]
Wanted to share a quick follow up. Within the past few hours SQA has mysteriously started working again. I've been developing some things in PyCharm and have gone through a number of installs and restarts for various packages, so I can't pinpoint what did it. So it's still functional, but I can't recreate what I did.
