### ISSUE TITLE
Can't download; aws host can't be resolved

### ISSUE THREAD

**Issue by pburkindine** [dteoh/SlowQuitApps#72]
╰─ brew cask install slowquitapps                                                                                    10154  08:13:46 
==> Caveats
  Accessibility permissions must be reset after updating or re-installing.

  Instructions are available in the README at https://github.com/dteoh/SlowQuitApps

==> Downloading https://github.com/dteoh/SlowQuitApps/releases/download/v0.8.0/SlowQuitApps.zip
######################################################################## 100.0%
curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
Error: Download failed on Cask 'slowquitapps' with message: Download failed: https://github.com/dteoh/SlowQuitApps/releases/download/v0.8.0/SlowQuitApps.zip

**Comment by pburkindine** [comment]
Also can't download from the releases page with the same error

**Comment by dteoh** [comment]
It is working for me.

This could just be an issue with Github itself or your local network/ISP.

**Comment by pburkindine** [comment]
@dteoh hmm, I'm not working through any VPN etc... I really would like to get a copy of this app, could you e-mail one to me possibly?  pburkind@gmail.com

**Comment by dteoh** [comment]
Sorry, but I'm not going to email any binaries. My suggestion is to try a different computer, probably on a different network as well. The error you are getting suggests either some DNS or firewall issue.

**Comment by pburkindine** [comment]
For whatever reason and apropos of nothing it is working today.  Thanks!
