### ISSUE TITLE
Show pop up every boot

### ISSUE THREAD

**Issue by deadcatssociety** [dteoh/SlowQuitApps#74]
<img width="460" alt="Screen Shot 2020-03-12 at 10 04 15 AM" src="https://user-images.githubusercontent.com/1787490/76477853-f0966600-6449-11ea-8007-da3bd44cc008.png">

Show this pop up every boot, even I select 'No'.

OS: macOS 10.15.3
App: 0.8.0

**Comment by dteoh** [comment]
It sounds like the app is auto starting through a legacy API. Try following the instructions here:

https://github.com/dteoh/SlowQuitApps/releases/tag/v0.7.0

**Comment by deadcatssociety** [comment]
Thanks, it works!
