### ISSUE TITLE
Can't configure delay for 0.8.0 on Catalina

### ISSUE THREAD

**Issue by lucianodinapoli** [dteoh/SlowQuitApps#76]
I installed 0.8.0 from the zip on Catalina, updated permissions, started app and quit with `$ killall SlowQuitApps`. When I try `defaults read com.dteoh.SlowQuitApps` I get the following error:

```
2020-03-16 14:26:46.085 defaults[20832:704634] 
Domain com.dteoh.SlowQuitApps does not exist
```
So I can't change the delay time for closing the apps. I tried uninstalling / opening / closing / removing accessibility permissions, nothing fixed it. The app works though...

**Comment by dteoh** [comment]
That is normal.

Just proceed with the write command.
