### ISSUE TITLE
⌘ + Q needs to be pressed until the timer ends.

### ISSUE THREAD

**Issue by jvlobo** [dteoh/SlowQuitApps#77]
I have SlowQuitApps on my laptop and I can use it by pressing ⌘ + Q, but then I can release the Q key and the timer still goes as long as I keep ⌘ pressed.

Now I have installed it on another computer and for it to work I have to keep both keys pressed until the timer ends.

Is there a way I can configure it as I have it on my laptop: only having to keep ⌘ pressed until the timer ends.

Thanks.

**Comment by dteoh** [comment]
What version are you using on the laptop? Not having to hold Q as well is a bug that was fixed years ago (#5).

At this stage, I doubt that I am going to reintroduce an option to recreate a bug because it will just complicate the overall key handling.

**Comment by jvlobo** [comment]
Thanks for the answer dteoh
A bug?? noo, it is very handy :(
In my laptop, I have version 0.2.1
Sad to hear that I won't be able to use it this way on the new computer, I'm super used to just not keep pressing the Q key :/
