### ISSUE TITLE
Why SlowQuitApps need mount?

### ISSUE THREAD

**Issue by nella17** [dteoh/SlowQuitApps#78]
I use `mount` command see `SloeQuitApps` mounted at weird location.

> $ mount
> ...
> /Applications/SlowQuitApps.app on /private/var/folders/z0/6cs0nx6s3yb6x2vd7xm7vfn40000gn/T/AppTranslocation/5CA6D5C4-05F0-48DD-822B-DFE9042D60B4 (nullfs, local, nodev, nosuid, read-only, nobrowse, mounted by nella17)

**Comment by dteoh** [comment]
I don't really understand the question or the context surrounding it.

The app doesn't do anything with filesystems. The only thing that comes to mind is that maybe the DMG is still mounted?

**Comment by nella17** [comment]
NO, dmg not mounted, I restart my MacBook, but this still mounted.

**Comment by nella17** [comment]
I don't known why, but use `xattr -dr com.apple.quarantine /Applications/SlowQuitApps.app` command can solve this problem.
https://apple.stackexchange.com/questions/262570/oddly-randomized-mounted-paths-in-sierra-for-certain-apps

**Comment by dteoh** [comment]
Thank you for the information. Closing this issue because this is how the OS works.
