### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by philipstancil** [dteoh/SlowQuitApps#8]
Hey! This is a great app, but I really only need it to work for Safari. Since it is universal, I'd like to remove it from the system, but I can't find it anywhere on my computer.

Can you guide me through the uninstall process?

Thanks!

**Comment by dteoh** [comment]
Use Activity Monitor to search for the "SlowQuitApps" process. Kill the process. Then delete the app from the Applications directory.

Hope this helps.

**Comment by philipstancil** [comment]
Thanks for the quick response! I appreciate it. I had never moved it to Applications, so it was working straight out of the Downloads folder. That's where I got confused. Appreciate the guidance!
