### ISSUE TITLE
Some apps do not quit (iTerm2)

### ISSUE THREAD

**Issue by 7Ds7** [dteoh/SlowQuitApps#9]
First and foremost a huge thank you for providing the app, since macOS Sierra came out, and [Karabiner](https://github.com/tekezo/Karabiner) stopped working with the only functionality that i used it for _cmd + Q_ **Twice** to quit application this has been driving me crazy.

Gladly you provided one alternative, although i just installed there is at least one app for which it does not work [iTerm2](http://iterm2.com/) as i did not found another suitable place to add ( ex: a list of incompatible apps ) i am posting it here.

As i try to quit iTerm2 the closing animation briefly appears and disappears without completing the cycle every time i press _cmd + Q_ and as such it never quits the app via shortcut.

A small side note or should i say personal preference, it would be great to have a way to make the quit timer more subtle, something like a size change via parameter just as the delay would be great.

Cheers and many thanks once again.

**Comment by dteoh** [comment]
I am also using Sierra and iTerm2 and have encountered no problems so far. Apart from making sure that iTerm2 is the focused application, this sounds like it could be some configuration setting within iTerm2 preventing itself from quitting (open SSH sessions, etc.).

**Comment by 7Ds7** [comment]
Strange, it is not a open SSH session in fact just one window open on localhost and it does that behaviour, even with no window open and the app focused.

But i looked into the settings and if i disable _iTerm -> Secure Keyboard Entry_ it works. Which kind of makes sense https://iterm2.com/documentation-menu-items.html

**Comment by dteoh** [comment]
Good to know 👍

**Comment by creynders** [comment]
I have no problems with iTerm, but I do with a few other apps like 1password and forticlient. Unfortunately they don't feature a "Secure Keyboard Entry" setting or some such.

**Comment by dteoh** [comment]
I tried with 1Password 6 and it works. 🤷‍♂️

There must be an issue somewhere else, maybe with conflicting software or other global key handlers.

**Comment by vamshi29292** [comment]
I too have a problem with iterm2

**Comment by 7Ds7** [comment]
there is no issue here it is iterm2 security https://github.com/dteoh/SlowQuitApps/issues/9#issuecomment-270417719
