### ISSUE TITLE
Issue with Mac M1

### ISSUE THREAD

**Issue by Tchoupinax** [dteoh/SlowQuitApps#94]
Hello,

I meet a problem while making working the application with a M1 MacBook Pro and I see that I'm not alone according to issues

- https://github.com/dteoh/SlowQuitApps/issues/82#issuecomment-970294114
- https://github.com/dteoh/SlowQuitApps/issues/92

The application has the right in settings but when I start it, it continues to ask the right.

How can we fix this issue ? You software is really amazing and I am missing it.

Thank you :)

**Comment by TheInkedEngineer** [comment]
The issue is here:

```
BOOL hasAccessibility() {
#if defined(DEBUG)
    return YES;
#else
    NSDictionary *options = @{(__bridge id)kAXTrustedCheckOptionPrompt: @YES};
    return AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)options);
#endif
}
```

I don't know any objc, nor I am familiar with these variables. If anyone is, the fix is pretty straightforward.

**Comment by blimeybloke** [comment]
Same issue for me on my M1 Macbook Air.  I love this app and have used it for years.  Hopefully someone can clone the project and do some housekeeping.  Mainly this bug.
Cheers!

**Comment by tracure1337** [comment]
Same here! Thanks in advance for the fix.

**Comment by Lessica** [comment]
Fixed. https://github.com/Lessica/SlowQuitApps/releases/tag/v0.8.1

**Comment by Tchoupinax** [comment]
Hello @Lessica!

Thank you for your work. I downloaded your release and try it, but I have the same result : I give authorisation to the app and restart it, but at the start, the app asks authorisation again. Does another people has tested this release and has the issue ?

**Comment by haydnhkim** [comment]
@Tchoupinax I also had the same problem. I repeated installing, executing, and deleting several times.
After several attempts, a notification asking whether to log in at system startup appeared, and from then on, it worked normally.

**Comment by Lessica** [comment]
> Hello @Lessica!
> 
> Thank you for your work. I downloaded your release and try it, but I have the same result : I give authorisation to the app and restart it, but at the start, the app asks authorisation again. Does another people has tested this release and has the issue ?

I think the macOS system needs more attempts to refresh caches of the authorization.

You need to repeat following steps a few times (I just tried once and it worked):
- `killall SlowQuitApps`
- Uninstall `dteoh’s` original version
- Remove `SlowQuitApps` from authorization list
- Install new version
- Launch it and add it to authorization list

**Comment by Tchoupinax** [comment]
Thanks @Lessica! 
I followed your step conscientiously and now it works :)

**Comment by Tchoupinax** [comment]
As author of the issue and as my issue is resolved, I now close it.
Thanks for all!

**Comment by ashutoshsaboo** [comment]
thank youuu @Lessica for your hard work !!! :D This helped me too!

**Comment by yafeng520** [comment]
It also works for me now! Thank you so much! @Lessica
